sonar.projectKey=giis-uniovi_retorch-st-fullteaching-puppeteer-python
sonar.organization=giis-uniovi
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=fullteaching_e2e
sonar.tests=tests
sonar.exclusions=**/tests/**,.git/**
sonar.python.version=3.12
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
