sonar.projectKey=giis-uniovi_retorch-st-fullteaching-cypress-js
sonar.organization=giis-uniovi
sonar.sources=cypress
sonar.exclusions=**/node_modules/**,**/downloads/**,**/screenshots/**,**/videos/**
